spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
  profiles:
    include: security   # DB profile 관리
  messages:
    basename: messages,errors,messages_en

logging.level:
  org.hibernate.type: trace