//package choi.bok.gg.domain.match.dto;
//
//import lombok.Data;
//
//// 이거는 벨로그에 나온 방식을 쓰자 (필드 몇개만)
//@Data
//public class ChallengesDto {
//
//    private int ;
//    private int ;
//    private int ;
//    private int ;
//    private int ;
//
//
//    "12AssistStreakCount": 1,
//            "abilityUses": 217,
//            "acesBefore15Minutes": 0,
//            "alliedJungleMonsterKills": 0,
//            "baronBuffGoldAdvantageOverThreshold": 1,
//            "baronTakedowns": 1,
//            "blastConeOppositeOpponentCount": 0,
//            "bountyGold": 0,
//            "buffsStolen": 0,
//            "completeSupportQuestInTime": 0,
//            "controlWardTimeCoverageInRiverOrEnemyHalf": 0.37751807189863157,
//            "controlWardsPlaced": 3,
//            "damagePerMinute": 617.0622535743723,
//            "damageTakenOnTeamPercentage": 0.25626944041033173,
//            "dancedWithRiftHerald": 0,
//            "deathsByEnemyChamps": 4,
//            "dodgeSkillShotsSmallWindow": 0,
//            "doubleAces": 0,
//            "dragonTakedowns": 2,
//            "earliestBaron": 1381.5429311418425,
//            "earliestDragonTakedown": 1557.0980225337935,
//            "earlyLaningPhaseGoldExpAdvantage": 0,
//            "effectiveHealAndShielding": 0,
//            "elderDragonKillsWithOpposingSoul": 0,
//            "elderDragonMultikills": 0,
//            "enemyChampionImmobilizations": 145,
//            "enemyJungleMonsterKills": 2,
//            "epicMonsterKillsNearEnemyJungler": 0,
//            "epicMonsterKillsWithin30SecondsOfSpawn": 0,
//            "epicMonsterSteals": 0,
//            "epicMonsterStolenWithoutSmite": 0,
//            "flawlessAces": 0,
//            "fullTeamTakedown": 1,
//            "gameLength": 2168.2014508058805,
//            "getTakedownsInAllLanesEarlyJungleAsLaner": 0,
//            "goldPerMinute": 317.036754368814,
//            "hadOpenNexus": 0,
//            "highestCrowdControlScore": 1,
//            "immobilizeAndKillWithAlly": 11,
//            "initialBuffCount": 0,
//            "initialCrabCount": 0,
//            "jungleCsBefore10Minutes": 0,
//            "junglerTakedownsNearDamagedEpicMonster": 0,
//            "kTurretsDestroyedBeforePlatesFall": 0,
//            "kda": 4,
//            "killAfterHiddenWithAlly": 1,
//            "killedChampTookFullTeamDamageSurvived": 0,
//            "killsNearEnemyTurret": 0,
//            "killsOnOtherLanesEarlyJungleAsLaner": 0,
//            "killsOnRecentlyHealedByAramPack": 0,
//            "killsUnderOwnTurret": 0,
//            "killsWithHelpFromEpicMonster": 0,
//            "knockEnemyIntoTeamAndKill": 6,
//            "landSkillShotsEarlyGame": 3,
//            "laneMinionsFirst10Minutes": 62,
//            "laningPhaseGoldExpAdvantage": 0,
//            "legendaryCount": 0,
//            "lostAnInhibitor": 0,
//            "maxCsAdvantageOnLaneOpponent": 4,
//            "maxKillDeficit": 1,
//            "maxLevelLeadLaneOpponent": 1,
//            "moreEnemyJungleThanOpponent": -118.50000008940697,
//            "multiKillOneSpell": 0,
//            "multiTurretRiftHeraldCount": 0,
//            "multikills": 0,
//            "multikillsAfterAggressiveFlash": 0,
//            "mythicItemUsed": 3068,
//            "outerTurretExecutesBefore10Minutes": 0,
//            "outnumberedKills": 0,
//            "outnumberedNexusKill": 0,
//            "perfectDragonSoulsTaken": 0,
//            "perfectGame": 0,
//            "pickKillWithAlly": 14,
//            "playedChampSelectPosition": 1,
//            "poroExplosions": 0,
//            "quickCleanse": 0,
//            "quickFirstTurret": 0,
//            "quickSoloKills": 0,
//            "riftHeraldTakedowns": 0,
//            "saveAllyFromDeath": 0,
//            "scuttleCrabKills": 0,
//            "skillshotsDodged": 23,
//            "skillshotsHit": 29,
//            "snowballsHit": 0,
//            "soloBaronKills": 0,
//            "soloKills": 0,
//            "stealthWardsPlaced": 2,
//            "survivedSingleDigitHpCount": 0,
//            "survivedThreeImmobilizesInFight": 5,
//            "takedownOnFirstTurret": 0,
//            "takedowns": 16,
//            "takedownsAfterGainingLevelAdvantage": 1,
//            "takedownsBeforeJungleMinionSpawn": 0,
//            "takedownsFirstXMinutes": 0,
//            "takedownsInAlcove": 0,
//            "takedownsInEnemyFountain": 0,
//            "teamBaronKills": 2,
//            "teamDamagePercentage": 0.17760799803084326,
//            "teamElderDragonKills": 0,
//            "teamRiftHeraldKills": 0,
//            "threeWardsOneSweeperCount": 0,
//            "tookLargeDamageSurvived": 1,
//            "turretPlatesTaken": 0,
//            "turretTakedowns": 5,
//            "turretsTakenWithRiftHerald": 0,
//            "twentyMinionsIn3SecondsCount": 0,
//            "unseenRecalls": 0,
//            "visionScoreAdvantageLaneOpponent": -0.02786308526992798,
//            "visionScorePerMinute": 0.6082215614504309,
//            "wardTakedowns": 5,
//            "wardTakedownsBefore20M": 0,
//            "wardsGuarded": 0
//}
